services:
  rabbitmq:
    container_name: spring-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25676:25676"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order:
    container_name: spring-rabbitmq-order
    image: spring-rabbit-mq-order:latest
    build:
      context: order
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  inventory:
    container_name: spring-rabbitmq-inventory
    image: spring-rabbit-mq-inventory:latest
    build:
      context: inventory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
