spring:
  application:
    name: order
  rabbitmq:
#    host: rabbitmq # if running everything in Docker
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
server:
  port: 8081
rabbitmq:
  queue:
    order:
      name: order
  exchange:
    order:
      name: order
  binding:
    order:
      name: order
