spring:
  application:
    name: inventory
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
rabbitmq:
  queue:
    order:
      name: order
  exchange:
    order:
      name: order
  binding:
    order:
      name: order
